auth_allow_cleartext = yes
auth_mechanisms = plain login

sql_driver = sqlite
sqlite_path = /state/users.db

passdb sql {
  query = SELECT imap_password_hash AS password \
    FROM users \
    WHERE imap_username = '%{user}' \
      AND status = 'active' \
      AND imap_password_hash != '!'
}

userdb sql {
  query = SELECT \
      5000 AS uid, \
      5000 AS gid, \
      '/var/mail/voiceinbox/users/' || id AS home, \
      '/var/mail/voiceinbox/users/' || id AS mail_path \
    FROM users \
    WHERE imap_username = '%{user}' \
      AND status = 'active' \
      AND imap_password_hash != '!'

  iterate_query = SELECT imap_username AS user \
    FROM users \
    WHERE status = 'active' \
      AND imap_password_hash != '!'
}
